# Generated by Django 5.0.14 on 2025-07-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_sessions', '0002_sessionreminder_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sessionreminder',
            table='reminder',
        ),
        migrations.AlterModelTable(
            name='sessionreview',
            table='review',
        ),
        migrations.AlterModelTable(
            name='skillswaprequest',
            table='swaprequest',
        ),
        migrations.AlterModelTable(
            name='skillswapsession',
            table='swapsession',
        ),
    ]
