# Generated by Django 5.0.14 on 2025-07-31 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('skill_request', 'Skill Swap Request'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined'), ('session_scheduled', 'Session Scheduled'), ('session_reminder', 'Session Reminder'), ('session_completed', 'Session Completed'), ('new_review', 'New Review'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_email', models.EmailField(help_text='Use your university email address', max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('graduate', 'Graduate'), ('phd', 'PhD')], max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Tell others about yourself', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('availability', models.TextField(blank=True, help_text='Describe your general availability for skill-swap sessions')),
                ('is_verified', models.BooleanField(default=False, help_text='University email verification status')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('total_sessions_taught', models.PositiveIntegerField(default=0)),
                ('total_sessions_learned', models.PositiveIntegerField(default=0)),
                ('average_rating_as_teacher', models.FloatField(default=0.0)),
                ('average_rating_as_learner', models.FloatField(default=0.0)),
                ('prefer_in_person', models.BooleanField(default=True)),
                ('prefer_online', models.BooleanField(default=True)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_in_app', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
