# Generated by Django 5.0.14 on 2025-07-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_updated_at_skillcategory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='desiredskill',
            table='desiredskill',
        ),
        migrations.AlterModelTable(
            name='offeredskill',
            table='offeredskill',
        ),
        migrations.AlterModelTable(
            name='skillcategory',
            table='category',
        ),
        migrations.AlterModelTable(
            name='skillmatch',
            table='match',
        ),
    ]
